-- Curated KAMIS -> agricultural_price_products mappings for the
-- combined livestock/egg batch, using the Stage 8A four-part mapping
-- key (source_commodity_id, source_classification, source_grade,
-- source_sex). Raw KAMIS values are stored exactly as observed, never
-- pre-joined or normalized -- the importer applies normalizeForMatching
-- to each of the three dimensions independently at lookup time, on both
-- the stored mapping row and the freshly-parsed KAMIS row.
--
-- 89 rows total: 2 Eggs, 43 Cattle, 18 Sheep, 16 Goat, 10 Chicken --
-- exactly the real observed combinations recomputed from the audit's
-- raw export data (see the accompanying products migration). No
-- theoretical combination is mapped; a KAMIS row that doesn't match one
-- of these 89 exact (commodity, classification, grade, sex) tuples
-- continues to quarantine as unmapped_product, exactly as designed --
-- including any new combination that appears in a future daily run.
insert into public.agricultural_price_source_product_map
  (source_id, source_commodity_id, source_commodity_name, source_classification, source_grade, source_sex, product_id) values
  ('kamis', '72', 'Eggs', 'Indigenous /Kenyeji', '-', '-', 'eggs-indigenous-kenyeji'),
  ('kamis', '72', 'Eggs', 'Exotic/Grade', '-', '-', 'eggs-exotic-grade'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 2', 'Female', 'cattle-mixed-grade-2-female'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 2', 'Male', 'cattle-mixed-grade-2-male'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 5', 'Male', 'cattle-mixed-grade-5-male'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 4', 'Female', 'cattle-mixed-grade-4-female'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 4', 'Male', 'cattle-mixed-grade-4-male'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 3', 'Female', 'cattle-mixed-grade-3-female'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 3', 'Male', 'cattle-mixed-grade-3-male'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 1', 'Female', 'cattle-mixed-grade-1-female'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 1', 'Male', 'cattle-mixed-grade-1-male'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 5', 'Female', 'cattle-zebu-grade-5-female'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 5', 'Male', 'cattle-zebu-grade-5-male'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 4', 'Female', 'cattle-zebu-grade-4-female'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 4', 'Male', 'cattle-zebu-grade-4-male'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 3', 'Female', 'cattle-zebu-grade-3-female'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 3', 'Male', 'cattle-zebu-grade-3-male'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 2', 'Female', 'cattle-zebu-grade-2-female'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 2', 'Male', 'cattle-zebu-grade-2-male'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 1', 'Female', 'cattle-zebu-grade-1-female'),
  ('kamis', '140', 'Cattle', 'Zebu', 'Grade 1', 'Male', 'cattle-zebu-grade-1-male'),
  ('kamis', '140', 'Cattle', 'Ayrshire', 'Grade 2', 'Male', 'cattle-ayrshire-grade-2-male'),
  ('kamis', '140', 'Cattle', 'Sahiwal', 'Grade 1', 'Male', 'cattle-sahiwal-grade-1-male'),
  ('kamis', '140', 'Cattle', 'Friesian', 'Grade 2', 'Male', 'cattle-friesian-grade-2-male'),
  ('kamis', '140', 'Cattle', 'Ayrshire', 'Grade 3', 'Female', 'cattle-ayrshire-grade-3-female'),
  ('kamis', '140', 'Cattle', 'Ayrshire', 'Grade 3', 'Male', 'cattle-ayrshire-grade-3-male'),
  ('kamis', '140', 'Cattle', 'Friesian', 'Grade 1', 'Female', 'cattle-friesian-grade-1-female'),
  ('kamis', '140', 'Cattle', 'Friesian', 'Grade 1', 'Male', 'cattle-friesian-grade-1-male'),
  ('kamis', '140', 'Cattle', 'Ayrshire', 'Grade 1', 'Female', 'cattle-ayrshire-grade-1-female'),
  ('kamis', '140', 'Cattle', 'Ayrshire', 'Grade 1', 'Male', 'cattle-ayrshire-grade-1-male'),
  ('kamis', '140', 'Cattle', 'Friesian', 'Grade 2', 'Female', 'cattle-friesian-grade-2-female'),
  ('kamis', '140', 'Cattle', 'Boran', 'Grade 2', 'Male', 'cattle-boran-grade-2-male'),
  ('kamis', '140', 'Cattle', 'Boran', 'Grade 2', 'Castrate', 'cattle-boran-grade-2-castrate'),
  ('kamis', '140', 'Cattle', 'Boran', 'Grade 2', 'Female', 'cattle-boran-grade-2-female'),
  ('kamis', '140', 'Cattle', 'Ayrshire', 'Grade 2', 'Female', 'cattle-ayrshire-grade-2-female'),
  ('kamis', '140', 'Cattle', 'Sahiwal', 'Grade 2', 'Female', 'cattle-sahiwal-grade-2-female'),
  ('kamis', '140', 'Cattle', 'Mixed', 'Grade 5', 'Female', 'cattle-mixed-grade-5-female'),
  ('kamis', '140', 'Cattle', 'Other', 'Grade 2', 'Male', 'cattle-other-grade-2-male'),
  ('kamis', '140', 'Cattle', 'Guernsey', 'Grade 2', 'Male', 'cattle-guernsey-grade-2-male'),
  ('kamis', '140', 'Cattle', 'Boran', 'Grade 1', 'Male', 'cattle-boran-grade-1-male'),
  ('kamis', '140', 'Cattle', 'Exotic', 'Grade 2', 'Male', 'cattle-exotic-grade-2-male'),
  ('kamis', '140', 'Cattle', 'Exotic', 'Grade 1', 'Male', 'cattle-exotic-grade-1-male'),
  ('kamis', '140', 'Cattle', 'Friesian', 'Grade 3', 'Male', 'cattle-friesian-grade-3-male'),
  ('kamis', '140', 'Cattle', 'Other', 'Grade 3', 'Male', 'cattle-other-grade-3-male'),
  ('kamis', '140', 'Cattle', 'Sahiwal', 'Grade 2', 'Male', 'cattle-sahiwal-grade-2-male'),
  ('kamis', '167', 'Sheep', 'Dorper', 'Grade 3', 'Male', 'sheep-dorper-grade-3-male'),
  ('kamis', '167', 'Sheep', 'Red Maasai', 'Grade 2', 'Female', 'sheep-red-maasai-grade-2-female'),
  ('kamis', '167', 'Sheep', 'Red Maasai', 'Grade 2', 'Male', 'sheep-red-maasai-grade-2-male'),
  ('kamis', '167', 'Sheep', 'Red Maasai', 'Grade 3', 'Female', 'sheep-red-maasai-grade-3-female'),
  ('kamis', '167', 'Sheep', 'Red Maasai', 'Grade 3', 'Male', 'sheep-red-maasai-grade-3-male'),
  ('kamis', '167', 'Sheep', 'Red Maasai', 'Grade 1', 'Female', 'sheep-red-maasai-grade-1-female'),
  ('kamis', '167', 'Sheep', 'Red Maasai', 'Grade 1', 'Male', 'sheep-red-maasai-grade-1-male'),
  ('kamis', '167', 'Sheep', 'Dorper', 'Grade 2', 'Male', 'sheep-dorper-grade-2-male'),
  ('kamis', '167', 'Sheep', 'Blackhead Persian', 'Grade 2', 'Female', 'sheep-blackhead-persian-grade-2-female'),
  ('kamis', '167', 'Sheep', 'Merino', 'Grade 2', 'Male', 'sheep-merino-grade-2-male'),
  ('kamis', '167', 'Sheep', 'Blackhead Persian', 'Grade 1', 'Male', 'sheep-blackhead-persian-grade-1-male'),
  ('kamis', '167', 'Sheep', 'Blackhead Persian', 'Grade 2', 'Male', 'sheep-blackhead-persian-grade-2-male'),
  ('kamis', '167', 'Sheep', 'Dorper', 'Grade 3', 'Female', 'sheep-dorper-grade-3-female'),
  ('kamis', '167', 'Sheep', 'Somali', 'Grade 2', 'Male', 'sheep-somali-grade-2-male'),
  ('kamis', '167', 'Sheep', 'Red Maasai', '-', 'Male', 'sheep-red-maasai-no-grade-male'),
  ('kamis', '167', 'Sheep', 'Blackhead Persian', 'Grade 1', 'Female', 'sheep-blackhead-persian-grade-1-female'),
  ('kamis', '167', 'Sheep', 'Dorper', 'Grade 2', 'Female', 'sheep-dorper-grade-2-female'),
  ('kamis', '167', 'Sheep', 'Blackhead Persian', 'Grade 3', 'Female', 'sheep-blackhead-persian-grade-3-female'),
  ('kamis', '168', 'Goat', 'Dairy Goats', 'Grade 3', 'Male', 'goat-dairy-goats-grade-3-male'),
  ('kamis', '168', 'Goat', 'East African Goat', 'Grade 2', 'Female', 'goat-east-african-goat-grade-2-female'),
  ('kamis', '168', 'Goat', 'East African Goat', 'Grade 2', 'Male', 'goat-east-african-goat-grade-2-male'),
  ('kamis', '168', 'Goat', 'Mixed', 'Grade 3', 'Female', 'goat-mixed-grade-3-female'),
  ('kamis', '168', 'Goat', 'Mixed', 'Grade 3', 'Male', 'goat-mixed-grade-3-male'),
  ('kamis', '168', 'Goat', 'Mixed', 'Grade 2', 'Female', 'goat-mixed-grade-2-female'),
  ('kamis', '168', 'Goat', 'Mixed', 'Grade 2', 'Male', 'goat-mixed-grade-2-male'),
  ('kamis', '168', 'Goat', 'Mixed', 'Grade 1', 'Female', 'goat-mixed-grade-1-female'),
  ('kamis', '168', 'Goat', 'Mixed', 'Grade 1', 'Male', 'goat-mixed-grade-1-male'),
  ('kamis', '168', 'Goat', 'East African Goat', 'Grade 1', 'Female', 'goat-east-african-goat-grade-1-female'),
  ('kamis', '168', 'Goat', 'Improved Kienyeji', 'Grade 2', 'Male', 'goat-improved-kienyeji-grade-2-male'),
  ('kamis', '168', 'Goat', 'East African Goat', 'Grade 1', 'Male', 'goat-east-african-goat-grade-1-male'),
  ('kamis', '168', 'Goat', 'Dairy Goats', 'Grade 2', 'Male', 'goat-dairy-goats-grade-2-male'),
  ('kamis', '168', 'Goat', 'Dairy Goats', 'Grade 2', 'Female', 'goat-dairy-goats-grade-2-female'),
  ('kamis', '168', 'Goat', 'East African Goat', 'Grade 3', 'Male', 'goat-east-african-goat-grade-3-male'),
  ('kamis', '168', 'Goat', 'Dairy Goats', 'Grade 3', 'Female', 'goat-dairy-goats-grade-3-female'),
  ('kamis', '227', 'Chicken', 'Indigenous', '-', 'Male', 'chicken-indigenous-male'),
  ('kamis', '227', 'Chicken', 'Improved Kienyeji', '-', 'Female', 'chicken-improved-kienyeji-female'),
  ('kamis', '227', 'Chicken', 'Improved Kienyeji', '-', 'Male', 'chicken-improved-kienyeji-male'),
  ('kamis', '227', 'Chicken', 'Indigenous', '-', 'Female', 'chicken-indigenous-female'),
  ('kamis', '227', 'Chicken', 'Broiler', '-', 'Male', 'chicken-broiler-male'),
  ('kamis', '227', 'Chicken', 'Layers', '-', 'Female', 'chicken-layers-female'),
  ('kamis', '227', 'Chicken', 'Layers', '-', 'Male', 'chicken-layers-male'),
  ('kamis', '227', 'Chicken', 'Broiler', '-', 'Female', 'chicken-broiler-female'),
  ('kamis', '227', 'Chicken', 'Exotic', '-', 'Male', 'chicken-exotic-male'),
  ('kamis', '227', 'Chicken', '-', '-', 'Female', 'chicken-unspecified-female');
